- name: Show CPU information
  ansible.builtin.debug:
    msg: "CPU Info: {{ ansible_facts['processor'] }}"

- name: Show number of CPUs
  ansible.builtin.debug:
    msg: "Number of CPUs: {{ ansible_facts['processor_cores'] }}"

- name: Inform if Hyper-Threading is not enabled
  ansible.builtin.debug:
    msg: "Hyper-Threading is not enabled."
  when: ansible_facts['processor_threads_per_core'] == 1