- name: Check if partition is already encrypted with LUKS
  shell:
    cmd: "cryptsetup isLuks {{ partition_info.partition }}"
  register: luks_check
  changed_when: false
  ignore_errors: true

- name: Encrypt the partition with LUKS
  shell:
    cmd: "echo '{{ encryption_passphrase }}' | cryptsetup -q luksFormat {{ encryption_options }} {{ partition_info.partition }}"
  when: luks_check.rc != 0

- name: Attempt to open encrypted partition
  shell:
    cmd: "echo '{{ encryption_passphrase }}' | cryptsetup luksOpen {{ partition_info.partition }} {{ partition_info.mapper_name }}"
  register: open_partition
  ignore_errors: true

- name: Check if cryptsetup open was successful
  debug:
    msg: "cryptsetup open failed: {{ open_partition.stderr }}"
  when: open_partition.failed

- name: Verify that the mapped device exists after opening
  shell:
    cmd: "ls /dev/mapper/{{ partition_info.mapper_name }}"
  register: mapper_device_check
  retries: 5
  delay: 2
  until: mapper_device_check.rc == 0
  changed_when: false
  failed_when: mapper_device_check.rc != 0

- name: Create filesystem on encrypted partition
  shell:
    cmd: "mkfs.ext4 /dev/mapper/{{ partition_info.mapper_name }}"
  ignore_errors: true

- name: Ensure mount point exists
  ansible.builtin.file:
    path: "{{ partition_info.mount_point }}"
    state: directory

- name: Mount the encrypted partition
  ansible.builtin.mount:
    path: "{{ partition_info.mount_point }}"
    src: "/dev/mapper/{{ partition_info.mapper_name }}"
    fstype: ext4
    opts: defaults
    state: mounted

- name: Configure /etc/crypttab for partition encryption
  ansible.builtin.lineinfile:
    path: /etc/crypttab
    line: "{{ partition_info.mapper_name }} {{ partition_info.partition }} none luks"
    create: yes

- name: Configure /etc/fstab for partition mount
  ansible.builtin.lineinfile:
    regexp: "^/dev/mapper/{{ partition_info.mapper_name }}"
    path: /etc/fstab
    line: "/dev/mapper/{{ partition_info.mapper_name }} {{ partition_info.mount_point }} ext4 defaults 0 2"
    create: yes
    insertafter: EOF