all:
  hosts:
    server1:
      ansible_host: 18.153.197.145
      ansible_user: ubuntu
      old_interface_name: enX0
      new_interface_name: net0
      partitions_to_encrypt:
        - partition: "/dev/xvdf"  # Specify the partition for the second disk
          mapper_name: "encrypted_second_disk"
          mount_point: "/mnt/encrypted_second"
        - partition: "/dev/xvda14"     # Specify the partition adjacent to the root partition
          mapper_name: "encrypted_adjacent_partition"
          mount_point: "/mnt/encrypted_adjacent"
