- name: Ensure required tools are installed (Debian-based systems)
  ansible.builtin.apt:
    name: grub2-common
    state: present

- name: Backup current GRUB configuration
  ansible.builtin.copy:
    src: /etc/default/grub
    dest: /etc/default/grub.bak
    remote_src: yes
    backup: yes

- name: Append CPU C-state settings to GRUB_CMDLINE_LINUX_DEFAULT
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="(.*)"'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="\1 intel_idle.max_cstate=0"'
    backrefs: yes

- name: Update GRUB configuration
  ansible.builtin.command:
    cmd: update-grub

- name: Reboot the system to apply changes
  ansible.builtin.reboot:
    msg: "Rebooting to apply CPU C-states settings."
    connect_timeout: 5
    reboot_timeout: 300